# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LakefsEnterprise < Formula
  desc "lakeFS Enterprise provides Git-like data version control with enterprise features including RBAC, SSO, and data replication."
  homepage "https://lakefs.io"
  version "1.101.0"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://treeverse-clients-us-east.s3.amazonaws.com/lakefs-enterprise/1.101.0/lakefs-enterprise_1.101.0_Darwin_x86_64.tar.gz"
      sha256 "7a943ee1390c7df4634be3b3f8662827622530b71868e21e9dd885424b7f393c"

      define_method(:install) do
        bin.install "lakectl"
        bin.install "lakefs"
      end
    end
    if Hardware::CPU.arm?
      url "https://treeverse-clients-us-east.s3.amazonaws.com/lakefs-enterprise/1.101.0/lakefs-enterprise_1.101.0_Darwin_arm64.tar.gz"
      sha256 "e6c4cf88fc0f19998f09af4a9c83be9d9c0d90d88b36bf2adff0e633f4cc55e3"

      define_method(:install) do
        bin.install "lakectl"
        bin.install "lakefs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://treeverse-clients-us-east.s3.amazonaws.com/lakefs-enterprise/1.101.0/lakefs-enterprise_1.101.0_Linux_x86_64.tar.gz"
      sha256 "664013f2257d11a5a511d5a9319162790ddb33d291cc64b6be16fa3a1fc294ae"
      define_method(:install) do
        bin.install "lakectl"
        bin.install "lakefs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://treeverse-clients-us-east.s3.amazonaws.com/lakefs-enterprise/1.101.0/lakefs-enterprise_1.101.0_Linux_arm64.tar.gz"
      sha256 "c36002aad52dcb69b52604097d90d2d9bf170bb2bc7ac83141cc124222e6671b"
      define_method(:install) do
        bin.install "lakectl"
        bin.install "lakefs"
      end
    end
  end
end
