# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LakefsEnterprise < Formula
  desc "lakeFS Enterprise provides Git-like data version control with enterprise features including RBAC, SSO, and data replication."
  homepage "https://lakefs.io"
  version "1.104.0"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://treeverse-clients-us-east.s3.amazonaws.com/lakefs-enterprise/1.104.0/lakefs-enterprise_1.104.0_Darwin_x86_64.tar.gz"
      sha256 "da432713d6a354fb82f3d340d73061b28c1793518855a0c68d30f180ecb61f89"

      define_method(:install) do
        bin.install "lakectl"
        bin.install "lakefs"
      end
    end
    if Hardware::CPU.arm?
      url "https://treeverse-clients-us-east.s3.amazonaws.com/lakefs-enterprise/1.104.0/lakefs-enterprise_1.104.0_Darwin_arm64.tar.gz"
      sha256 "538322c48750f403cd5692da0cd8f4f4cd20c34cfffe70712bee97663df95e29"

      define_method(:install) do
        bin.install "lakectl"
        bin.install "lakefs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://treeverse-clients-us-east.s3.amazonaws.com/lakefs-enterprise/1.104.0/lakefs-enterprise_1.104.0_Linux_x86_64.tar.gz"
      sha256 "476fb14e17903266f614d769fc58c32549aaa6718469d47f051b3de0a3ea6b0a"
      define_method(:install) do
        bin.install "lakectl"
        bin.install "lakefs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://treeverse-clients-us-east.s3.amazonaws.com/lakefs-enterprise/1.104.0/lakefs-enterprise_1.104.0_Linux_arm64.tar.gz"
      sha256 "176b5191430868c270f1dff8816f01b8ec3a43629d264916b3f69bfa6f0b20fd"
      define_method(:install) do
        bin.install "lakectl"
        bin.install "lakefs"
      end
    end
  end
end
